spring.application.name=code-challenge

management.endpoints.web.exposure.include=health,info

spring.cache.cache-names=repositories
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=5m,recordStats

github.api.base-url=https://api.github.com
github.api.git-hub-api-version=2026-03-10
